export interface RitualEvent {
  id: string;
  dayNumber: number;
  hindiName: string;
  englishName: string;
  tithiHindi: string;
  tithiEnglish: string;
  dateISO: string; // YYYY-MM-DD
  targetTimeIST: string; // ISO string representing the key ritual moment (IST)
  ritualType: 'nahay_khay' | 'kharna' | 'sandhya_arghya' | 'usha_arghya' | 'parna';
  shortDesc: string;
  shortDescEn?: string;
  offerings: string[];
  offeringsEn?: string[];
  iconName: string;
}

export interface CityLocation {
  id: string;
  nameEn: string;
  nameHi: string;
  state: string;
  lat: number;
  lng: number;
  popularRiverGhat: string;
}

export const CHHATH_YEAR = 2026;

// Centralized Chhath 2026 Ritual Calendar (Kartik Shukla Chaturthi to Saptami)
export const CHHATH_RITUALS_2026: RitualEvent[] = [
  {
    id: 'day-1-nahay-khay',
    dayNumber: 1,
    hindiName: 'नहाय-खाय',
    englishName: 'Nahay-Khay',
    tithiHindi: 'कार्तिक शुक्ल चतुर्थी',
    tithiEnglish: 'Kartik Shukla Chaturthi',
    dateISO: '2026-11-13',
    targetTimeIST: '2026-11-13T09:00:00+05:30',
    ritualType: 'nahay_khay',
    shortDesc: 'पवित्र नदी स्नान, आत्मशुद्धि और कद्दू-भात का सात्विक महाप्रसाद।',
    shortDescEn: 'Sacred river bath, inner cleansing, and pure satvik meal of bottle gourd and rice (Kaddu-Bhat).',
    offerings: ['सेंधा नमकयुक्त कद्दू (लौकी)', 'अरवा चावल', 'चने की दाल', 'गंगाजल'],
    offeringsEn: ['Bottle Gourd with Rock Salt (Kaddu)', 'Arwa Rice', 'Chana Dal', 'Holy River Water'],
    iconName: 'Sparkles',
  },
  {
    id: 'day-2-kharna',
    dayNumber: 2,
    hindiName: 'खरना',
    englishName: 'Kharna',
    tithiHindi: 'कार्तिक शुक्ल पंचमी',
    tithiEnglish: 'Kartik Shukla Panchami',
    dateISO: '2026-11-14',
    targetTimeIST: '2026-11-14T17:45:00+05:30',
    ritualType: 'kharna',
    shortDesc: 'दिनभर निर्जला व्रत, शाम को गुड़ की रसिया-खीर व रोटी का नैवेद्य और 36 घंटे के निर्जला तप का शुभारंभ।',
    shortDescEn: 'Full-day waterless fast, evening offering of jaggery kheer (Rasiya) & rotis, beginning the 36-hour fast.',
    offerings: ['गुड़ की रसियाव (खीर)', 'घी चुपड़ी गेहूं की रोटी', 'केले का फल', 'तुलसी दल', 'गंगाजल'],
    offeringsEn: ['Jaggery Rasiyaw (Kheer)', 'Ghee Wheat Rotis', 'Ripe Bananas', 'Holy Tulsi Leaves', 'Ganga Jal'],
    iconName: 'Flame',
  },
  {
    id: 'day-3-sandhya-arghya',
    dayNumber: 3,
    hindiName: 'संध्या अर्घ्य (पहला अर्घ्य)',
    englishName: 'Sandhya Arghya',
    tithiHindi: 'कार्तिक शुक्ल षष्ठी',
    tithiEnglish: 'Kartik Shukla Shashthi',
    dateISO: '2026-11-15',
    targetTimeIST: '2026-11-15T17:05:00+05:30',
    ritualType: 'sandhya_arghya',
    shortDesc: 'नदी घाट पर अस्ताचलगामी (डूबते) सूर्य देव को बांस के सूप और दौरा से प्रथम अर्घ्य अर्पण।',
    shortDescEn: 'Offering the first sacred Arghya to the setting sun at the riverbank with woven bamboo soop and daura.',
    offerings: [
      'शुद्ध घी का ठेकुआ',
      'कसार (चावल के लड्डू)',
      'पत्ता लगा ताजा गन्ना (ईख)',
      'डाभ नींबू',
      'नारियल व केला घौद',
      'अदरक-हल्दी का हरा पौधा',
      'मिट्टी का चौमुख दीया',
    ],
    offeringsEn: [
      'Pure Ghee Thekua',
      'Kasaar (Rice Flour Ladoos)',
      'Fresh Whole Sugarcane',
      'Daabh Pomelo Lemon',
      'Coconut & Banana Bunches',
      'Ginger & Turmeric Shoots',
      'Four-Wick Clay Diya',
    ],
    iconName: 'SunMedium',
  },
  {
    id: 'day-4-usha-arghya',
    dayNumber: 4,
    hindiName: 'उषा अर्घ्य व पारण',
    englishName: 'Usha Arghya & Parna',
    tithiHindi: 'कार्तिक शुक्ल सप्तमी',
    tithiEnglish: 'Kartik Shukla Saptami',
    dateISO: '2026-11-16',
    targetTimeIST: '2026-11-16T06:12:00+05:30',
    ritualType: 'usha_arghya',
    shortDesc: 'उदीयमान सूर्य देव को दूसरा अर्घ्य, मंगलकामनाएं और पारण के साथ 36 घंटे के निर्जला महापर्व का समापन।',
    shortDescEn: 'Offering the second Arghya to the rising sun, receiving blessings, and breaking the 36-hour fast (Parna).',
    offerings: ['गाय का कच्चा दूध', 'गंगाजल', 'ताजा ठेकुआ व कसार', 'अदरक का टुकड़ा', 'सूप में सजे मौसमी फल'],
    offeringsEn: ['Fresh Cow Milk', 'Ganga Jal', 'Fresh Thekua & Kasaar', 'Raw Ginger', 'Riverbank Offerings'],
    iconName: 'Sunrise',
  },
];

// Fallback date for Next Chhath (2027)
export const NEXT_CHHATH_START = '2027-11-02T06:00:00+05:30';

// Curated List of Cities for Realtime Astronomical Calculations
export const SUPPORTED_CITIES: CityLocation[] = [
  {
    id: 'patna',
    nameEn: 'Patna',
    nameHi: 'पटना',
    state: 'Bihar',
    lat: 25.5941,
    lng: 85.1376,
    popularRiverGhat: 'दीघा घाट / कलेक्ट्रेट घाट (गंगा नदी)',
  },
  {
    id: 'varanasi',
    nameEn: 'Varanasi',
    nameHi: 'वाराणसी',
    state: 'Uttar Pradesh',
    lat: 25.3176,
    lng: 82.9739,
    popularRiverGhat: 'दशाश्वमेध घाट / अस्सी घाट (गंगा नदी)',
  },
  {
    id: 'ranchi',
    nameEn: 'Ranchi',
    nameHi: 'रांची',
    state: 'Jharkhand',
    lat: 23.3441,
    lng: 85.3096,
    popularRiverGhat: 'बड़ा तालाब / हटिया डैम',
  },
  {
    id: 'kolkata',
    nameEn: 'Kolkata',
    nameHi: 'कोलकाता',
    state: 'West Bengal',
    lat: 22.5726,
    lng: 88.3639,
    popularRiverGhat: 'बाबू घाट / प्रिंसेप घाट (हुगली नदी)',
  },
  {
    id: 'delhi',
    nameEn: 'Delhi NCR',
    nameHi: 'दिल्ली एनसीआर',
    state: 'Delhi',
    lat: 28.6139,
    lng: 77.209,
    popularRiverGhat: 'आईटीओ घाट / कालिंदी कुंज (यमुना नदी)',
  },
  {
    id: 'mumbai',
    nameEn: 'Mumbai',
    nameHi: 'मुंबई',
    state: 'Maharashtra',
    lat: 19.076,
    lng: 72.8777,
    popularRiverGhat: 'जुहू चौपाटी / गिरगांव चौपाटी',
  },
  {
    id: 'bengaluru',
    nameEn: 'Bengaluru',
    nameHi: 'बेंगलुरु',
    state: 'Karnataka',
    lat: 12.9716,
    lng: 77.5946,
    popularRiverGhat: 'उल्सूर झील / संकी टैंक',
  },
  {
    id: 'lucknow',
    nameEn: 'Lucknow',
    nameHi: 'लखनऊ',
    state: 'Uttar Pradesh',
    lat: 26.8467,
    lng: 80.9462,
    popularRiverGhat: 'झूलेलाल वाटिका घाट (गोमती नदी)',
  },
  {
    id: 'gaya',
    nameEn: 'Gaya',
    nameHi: 'गया',
    state: 'Bihar',
    lat: 24.7914,
    lng: 85.0002,
    popularRiverGhat: 'देवघाट (फल्गु नदी)',
  },
  {
    id: 'muzaffarpur',
    nameEn: 'Muzaffarpur',
    nameHi: 'मुजफ्फरपुर',
    state: 'Bihar',
    lat: 26.1209,
    lng: 85.3647,
    popularRiverGhat: 'सिकंदरपुर सीढ़ी घाट (बूढ़ी गंडक नदी)',
  },
  {
    id: 'bhagalpur',
    nameEn: 'Bhagalpur',
    nameHi: 'भागलपुर',
    state: 'Bihar',
    lat: 25.2425,
    lng: 86.9842,
    popularRiverGhat: 'बरारी घाट (गंगा नदी)',
  },
  {
    id: 'darbhanga',
    nameEn: 'Darbhanga',
    nameHi: 'दरभंगा',
    state: 'Bihar',
    lat: 26.1542,
    lng: 85.8918,
    popularRiverGhat: 'हराही तालाब / बागमती नदी',
  },
];

// Curated Official Music Playlists
export const MUSIC_PLAYLISTS = {
  ytMusic: {
    title: 'छठ पूजा स्पेशल — YouTube Music',
    subtitle: 'Chhath Mahaparv Devotional Playlist',
    playlistId: 'PLfYmGnrirAFQ',
    directUrl: 'https://music.youtube.com/playlist?list=PLfYmGnrirAFQ&si=i0uEsFaG2nlLlNmy',
    credit: 'Official YouTube Music Streaming Radio',
  },
  spotify: {
    title: 'छठ पूजा के पावन गीत — Spotify Special',
    subtitle: 'Official Chhath Mahaparv Devotional Playlist',
    playlistId: '37i9dQZF1DX8AYACgIFhwm',
    directUrl: 'https://open.spotify.com/playlist/37i9dQZF1DX8AYACgIFhwm?si=25ef0539dfa545e1',
    embedUrl: 'https://open.spotify.com/embed/playlist/37i9dQZF1DX8AYACgIFhwm?utm_source=generator&si=25ef0539dfa545e1',
    credit: 'Official Spotify Music Player',
  },
};

export interface SongRecord {
  id: string;
  trackNum: string;
  hindiTitle: string;
  romanTitle: string;
  artist: string;
  year: string;
  videoId?: string;
}

export const CHHATH_SONGS: SongRecord[] = [
  {
    id: "s_1",
    trackNum: "001",
    videoId: "_Eml7TWyTt8",
    hindiTitle: "उग हे सुरुजदेव भेल भिनसरवा",
    romanTitle: "Uga Ho Surujdev Bhel Bhinsarva",
    artist: "अनुराधा पौडवाल (Anuradha Paudwal)",
    year: "1994",
  },
  {
    id: "s_2",
    trackNum: "002",
    videoId: "3G4Ieyk7hV0",
    hindiTitle: "कांच ही बांस के बहंगिया",
    romanTitle: "Kaanch Hi Baans Ke Bahangiya",
    artist: "अनुराधा पौडवाल (Anuradha Paudwal)",
    year: "1992",
  },
  {
    id: "s_3",
    trackNum: "003",
    videoId: "EFIRAw14dXc",
    hindiTitle: "हो दीनानाथ",
    romanTitle: "Ho Deenanath",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1986",
  },
  {
    id: "s_4",
    trackNum: "004",
    videoId: "r9FPkvI2lKU",
    hindiTitle: "मारबो रे सुगवा धनुष से",
    romanTitle: "Marbo Re Sugwa Dhanukh",
    artist: "अनुराधा पौडवाल (Anuradha Paudwal)",
    year: "1994",
  },
  {
    id: "s_5",
    trackNum: "005",
    videoId: "IzDm2ndwWqg",
    hindiTitle: "अंगना में पोखरी खनाइब",
    romanTitle: "Angna Mein Pokhri Khonaib",
    artist: "कविता पौडवाल (Kavita Paudwal)",
    year: "1998",
  },
  {
    id: "s_6",
    trackNum: "006",
    videoId: "WYkrgIZFcZw",
    hindiTitle: "पहिले पहिल छठी मैया",
    romanTitle: "Pahile Pahil Chhathi Maiya",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "2016",
  },
  {
    id: "s_7",
    trackNum: "007",
    videoId: "qUeuWi81PmM",
    hindiTitle: "केलवा के पात पर",
    romanTitle: "Kelwa Ke Paat Par",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1991",
  },
  {
    id: "s_8",
    trackNum: "008",
    videoId: "iPMpi-mFJhk",
    hindiTitle: "छठ के बरतिया",
    romanTitle: "Chhath Ke Baratiya",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1995",
  },
  {
    id: "s_9",
    trackNum: "009",
    videoId: "MBu0ug2FExE",
    hindiTitle: "राखो सभे छठ के बरत",
    romanTitle: "Rakho Sabhe Chhath Ke Barat",
    artist: "कविता पौडवाल (Kavita Paudwal)",
    year: "2000",
  },
  {
    id: "s_10",
    trackNum: "010",
    videoId: "5_PsGmN6SEg",
    hindiTitle: "पटना के हाट पर नरियर",
    romanTitle: "Patna Ke Haat Per Naariyar",
    artist: "कविता पौडवाल (Kavita Paudwal)",
    year: "2001",
  },
  {
    id: "s_11",
    trackNum: "011",
    videoId: "sdHZn1BFhHY",
    hindiTitle: "उठाउ सुरुज भइले बिहान",
    romanTitle: "Uthau Suruj Bhaile Bihaan",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1989",
  },
  {
    id: "s_12",
    trackNum: "012",
    videoId: "UJpFa66hFs0",
    hindiTitle: "जोड़े जोड़े फलवा सुरुज देव",
    romanTitle: "Jode Jode Falwa",
    artist: "पवन सिंह और पलक मुच्छल",
    year: "2018",
  },
  {
    id: "s_13",
    trackNum: "013",
    videoId: "rT95omCKS_w",
    hindiTitle: "अरघ के बेर",
    romanTitle: "Aragh Ke Ber",
    artist: "अनुराधा पौडवाल (Anuradha Paudwal)",
    year: "1996",
  },
  {
    id: "s_14",
    trackNum: "014",
    videoId: "oJ1h2TtZdjw",
    hindiTitle: "असिया पूरन होय",
    romanTitle: "Asiya Puran Hoy",
    artist: "कविता पौडवाल (Kavita Paudwal)",
    year: "2002",
  },
  {
    id: "s_15",
    trackNum: "015",
    videoId: "mv76jVDO2lU",
    hindiTitle: "केलवा के पात पर (क्लासिक)",
    romanTitle: "Kelwa Ke Paat Par",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1989",
  },
  {
    id: "s_16",
    trackNum: "016",
    videoId: "sImm-ZbPPqM",
    hindiTitle: "छठी मैया आई ना दुअरिया",
    romanTitle: "Chhathi Maiya Aayi Na Duaariya",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1993",
  },
  {
    id: "s_17",
    trackNum: "017",
    videoId: "GsUKvpag0zc",
    hindiTitle: "कार्तिक मास इजोरिया",
    romanTitle: "Kartik Maas Ijoriya",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1994",
  },
  {
    id: "s_18",
    trackNum: "018",
    videoId: "FU1z1CLJFzM",
    hindiTitle: "बांझि केवड़वा धइले ठाढ़",
    romanTitle: "Baanjhi Kewdwa Dhaile Thaadh",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1990",
  },
  {
    id: "s_19",
    trackNum: "019",
    videoId: "WYomV6rWD7A",
    hindiTitle: "कार्तिक महिनवां के",
    romanTitle: "Kartik Mahinavan Ke",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1992",
  },
  {
    id: "s_20",
    trackNum: "020",
    videoId: "t-XIdZX5Hs8",
    hindiTitle: "उठाउ सुरुज भइले बिहान",
    romanTitle: "Uthau Suruj Bhaile Bihaan",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1991",
  },
  {
    id: "s_21",
    trackNum: "021",
    videoId: "BOuCqbOhJG8",
    hindiTitle: "केहन समैया अइले",
    romanTitle: "Kehan Samaiya Aele",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1996",
  },
  {
    id: "s_22",
    trackNum: "022",
    videoId: "pQN9E-XcCtI",
    hindiTitle: "उगिहें सुरुज गोसइयां हे",
    romanTitle: "Ugihen Suraj Gosaiyan Hey",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1997",
  },
  {
    id: "s_23",
    trackNum: "023",
    videoId: "EzaBCrL91JE",
    hindiTitle: "हे छठी मैया",
    romanTitle: "Hey Chhathi Maiya",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1990",
  },
  {
    id: "s_24",
    trackNum: "024",
    videoId: "v8yOzkbsMaQ",
    hindiTitle: "छठी मैया बुलाये",
    romanTitle: "Chhathi Maiya Bulaye",
    artist: "विशाल मिश्रा (Vishal Mishra)",
    year: "2023",
  },
  {
    id: "s_25",
    trackNum: "025",
    videoId: "mifsBkmS828",
    hindiTitle: "कोपी कोपी बोलेली",
    romanTitle: "Kopi Kopi Boleli",
    artist: "देवी (Devi)",
    year: "2006",
  },
  {
    id: "s_26",
    trackNum: "026",
    videoId: "mFqvZp8FLhg",
    hindiTitle: "जल बीच खड़ा होई (जोड़े जोड़े फलवा)",
    romanTitle: "Jal Beech Khada Hoee",
    artist: "पवन सिंह (Pawan Singh)",
    year: "2019",
  },
  {
    id: "s_27",
    trackNum: "027",
    videoId: "KQqoli_tVVY",
    hindiTitle: "दुखवा मिटाईं छठी मैया",
    romanTitle: "Dukhwa Mitayin Chhathi Maiya",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "2015",
  },
  {
    id: "s_28",
    trackNum: "028",
    videoId: "IAN6JGZ726A",
    hindiTitle: "देईं सुरुज के अरघिया",
    romanTitle: "Dei Suruj Ke Arghiya",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1999",
  },
  {
    id: "s_29",
    trackNum: "029",
    videoId: "oWGtaIu9dG0",
    hindiTitle: "कांच ही बांस के बहंगिया",
    romanTitle: "Kaanch Hi Baans Ke Bahangiya",
    artist: "देवी (Devi)",
    year: "2005",
  },
  {
    id: "s_30",
    trackNum: "030",
    videoId: "-D98lv8lCgY",
    hindiTitle: "देवी तूं हौ महान",
    romanTitle: "Devi Toon Hau Mahan",
    artist: "पवन सिंह (Pawan Singh)",
    year: "2017",
  },
  {
    id: "s_31",
    trackNum: "031",
    videoId: "2uBDCC4b0go",
    hindiTitle: "हो दीनानाथ",
    romanTitle: "Ho Dinanath",
    artist: "अनुराधा पौडवाल (Anuradha Paudwal)",
    year: "1995",
  },
  {
    id: "s_32",
    trackNum: "032",
    videoId: "54qMF6i7FSg",
    hindiTitle: "जोड़े जोड़े सुपवा तोरा",
    romanTitle: "Jode Jode Supwa Tora",
    artist: "आनंद मोहन (Anand Mohan)",
    year: "2008",
  },
  {
    id: "s_33",
    trackNum: "033",
    videoId: "A3eyl67X_bc",
    hindiTitle: "घूंटी भर धोती भींजे",
    romanTitle: "Ghuti Bhara Dhoti Bhinje",
    artist: "अनु दुबे (Anu Dubey)",
    year: "2018",
  },
  {
    id: "s_34",
    trackNum: "034",
    videoId: "lsLPTMy-suI",
    hindiTitle: "आदित मनइला",
    romanTitle: "Aadit Manaila",
    artist: "अनुराधा पौडवाल (Anuradha Paudwal)",
    year: "1997",
  },
  {
    id: "s_35",
    trackNum: "035",
    videoId: "qGiyP8gd_D8",
    hindiTitle: "उग हो सुरुज देव",
    romanTitle: "Ug Ho Suraj Dev",
    artist: "अनुराधा पौडवाल (Anuradha Paudwal)",
    year: "1996",
  },
  {
    id: "s_36",
    trackNum: "036",
    videoId: "tHvnucD_rpk",
    hindiTitle: "केलवा के पात पर",
    romanTitle: "Kelwa Ke Paat Par",
    artist: "देवी (Devi)",
    year: "2007",
  },
  {
    id: "s_37",
    trackNum: "037",
    videoId: "6wh1Z-SWv7k",
    hindiTitle: "नदिया के तीरे-तीरे",
    romanTitle: "Nadiya Ke Teere Teere",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1993",
  },
  {
    id: "s_38",
    trackNum: "038",
    videoId: "fZ-7lXHONw8",
    hindiTitle: "सात हीं घोड़वा सुरुज देव",
    romanTitle: "Saat Hin Ghodva Suraj Dev",
    artist: "अनुराधा पौडवाल (Anuradha Paudwal)",
    year: "1994",
  },
  {
    id: "s_39",
    trackNum: "039",
    videoId: "Iyc05JCoGTw",
    hindiTitle: "पूजन के रे बेरिया",
    romanTitle: "Pujan Ke Re Beriya",
    artist: "पवन सिंह (Pawan Singh)",
    year: "2019",
  },
  {
    id: "s_40",
    trackNum: "040",
    videoId: "nHKzAi-KF1s",
    hindiTitle: "दरसन दीहीं ना आपन",
    romanTitle: "Darsan Dihin Na Apan",
    artist: "अनुराधा पौडवाल (Anuradha Paudwal)",
    year: "1998",
  },
  {
    id: "s_41",
    trackNum: "041",
    videoId: "PjwWd97HH04",
    hindiTitle: "उग हो सुरुजदेव",
    romanTitle: "Ugg Ho Surajdev",
    artist: "देवी (Devi)",
    year: "2008",
  },
  {
    id: "s_42",
    trackNum: "042",
    videoId: "-U8Un3nb-GI",
    hindiTitle: "जोड़े जोड़े नरियर",
    romanTitle: "Jode Jode Nariyal",
    artist: "देवी (Devi)",
    year: "2009",
  },
  {
    id: "s_43",
    trackNum: "043",
    videoId: "_9BrRUR8G6E",
    hindiTitle: "बेरिया के बेरी तोहे",
    romanTitle: "Beriya Ke Beri Tohe",
    artist: "अनुराधा पौडवाल (Anuradha Paudwal)",
    year: "1999",
  },
  {
    id: "s_44",
    trackNum: "044",
    videoId: "rnelNKdPrhQ",
    hindiTitle: "बरतिने के अंगना में",
    romanTitle: "Baratine Ke Agana Mein",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1994",
  },
  {
    id: "s_45",
    trackNum: "045",
    videoId: "e-0FjvSOaw8",
    hindiTitle: "जय छठी मैया",
    romanTitle: "Jai Chhathi Maiya",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "2001",
  },
  {
    id: "s_46",
    trackNum: "046",
    videoId: "z7cBE-47e5E",
    hindiTitle: "कांच ही बांस के बहंगिया",
    romanTitle: "Kanch Hi Bans Ke Bahangiya",
    artist: "ज्योति तिवारी (Jyoti Tiwari)",
    year: "2016",
  },
  {
    id: "s_47",
    trackNum: "047",
    videoId: "_SQqPSrX4fk",
    hindiTitle: "छपरा छठ मनाएंगे",
    romanTitle: "Chhapra Chhat Manayenge",
    artist: "खेसारी लाल यादव (Khesari Lal Yadav)",
    year: "2020",
  },
  {
    id: "s_48",
    trackNum: "048",
    videoId: "XYUQffUNAtA",
    hindiTitle: "कहवां पइबो सोने के कटोरवा",
    romanTitle: "Kahawa Paibo Sone Ke Katorwa",
    artist: "अनु दुबे (Anu Dubey)",
    year: "2017",
  },
  {
    id: "s_49",
    trackNum: "049",
    videoId: "VllE5pk2xZg",
    hindiTitle: "छठ व्रत के कमाल",
    romanTitle: "Chhath Vrat Ke Kamal",
    artist: "पायल मलिक (Payal Malik)",
    year: "2021",
  },
  {
    id: "s_50",
    trackNum: "050",
    videoId: "dUw65GZsVjc",
    hindiTitle: "हे छठी मैया (शाश्वत स्वर)",
    romanTitle: "Hey Chhathi Maiya",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1990",
  },
  {
    id: "s_51",
    trackNum: "051",
    videoId: "u35Xr6OdHjk",
    hindiTitle: "खेसरिया के कोसी",
    romanTitle: "Khesariya Ke Khosi",
    artist: "खेसारी लाल यादव (Khesari Lal Yadav)",
    year: "2021",
  },
  {
    id: "s_52",
    trackNum: "052",
    videoId: "GecC91GMrS4",
    hindiTitle: "छठी मैया के देहल",
    romanTitle: "Chati Maiya Ke Dehal",
    artist: "मनोज तिवारी (Manoj Tiwari)",
    year: "2005",
  },
  {
    id: "s_53",
    trackNum: "053",
    videoId: "EMVa61kWfK4",
    hindiTitle: "गंगा जी के घाटे",
    romanTitle: "Ganga Ji Ke Ghaate",
    artist: "देवी (Devi)",
    year: "2006",
  },
  {
    id: "s_54",
    trackNum: "054",
    videoId: "YC17AMwqK0c",
    hindiTitle: "जय छठी मैया (आरती)",
    romanTitle: "Jai Chati Maiya",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1998",
  },
  {
    id: "s_55",
    trackNum: "055",
    videoId: "P3QKIJoAkqc",
    hindiTitle: "पटना के घटिया",
    romanTitle: "Patna Ke Ghatiya",
    artist: "अक्षरा सिंह (Akshara Singh)",
    year: "2022",
  },
  {
    id: "s_56",
    trackNum: "056",
    videoId: "_ON2Kq_Pydc",
    hindiTitle: "चइती के छठवा",
    romanTitle: "Chayiti Ke Chathwa",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "2010",
  },
  {
    id: "s_57",
    trackNum: "057",
    videoId: "1zVvFfHfc4w",
    hindiTitle: "हे छठी मैया (आरती)",
    romanTitle: "Hey Chhatthi Maiya (Aarti)",
    artist: "कल्पना पटवारी (Kalpana Patowary)",
    year: "2012",
  },
  {
    id: "s_58",
    trackNum: "058",
    videoId: "mW5sA8f920o",
    hindiTitle: "जा जा ये चंदा",
    romanTitle: "Ja Ja Ye Chanda",
    artist: "पलक मुच्छल (Palak Muchhal)",
    year: "2019",
  },
  {
    id: "s_59",
    trackNum: "059",
    videoId: "yOBnZSQhNyw",
    hindiTitle: "बहंगिया लचकत घाटे जाला हो",
    romanTitle: "Bahangiya Lachkat Ghate Jala Ho",
    artist: "खेसारी लाल यादव (Khesari Lal Yadav)",
    year: "2020",
  },
  {
    id: "s_60",
    trackNum: "060",
    videoId: "gcMaEp5dh8k",
    hindiTitle: "हे छठी माई कृपा तोहार",
    romanTitle: "He Chhati Mayi Kripa Tohar",
    artist: "खेसारी लाल यादव (Khesari Lal Yadav)",
    year: "2021",
  },
  {
    id: "s_61",
    trackNum: "061",
    videoId: "QFW9RnrfQhc",
    hindiTitle: "घाटवा पा चांदनी तानाय",
    romanTitle: "Ghatva Pa Chandni Tanaay",
    artist: "अनुराधा पौडवाल (Anuradha Paudwal)",
    year: "1994",
  },
  {
    id: "s_62",
    trackNum: "062",
    videoId: "gkRLiyZfQuY",
    hindiTitle: "जगमग जरे दियानवा नु हो",
    romanTitle: "Jagmag Jare Diyanwa Nu Ho",
    artist: "कल्पना पटवारी (Kalpana Patowary)",
    year: "2014",
  },
  {
    id: "s_63",
    trackNum: "063",
    videoId: "hy2eTEBozec",
    hindiTitle: "पटना के हाट पर नरियर",
    romanTitle: "Patna Ke Haat Per Naariyar",
    artist: "कविता पौडवाल (Kavita Paudwal)",
    year: "2001",
  },
  {
    id: "s_64",
    trackNum: "064",
    videoId: "yZrXWMSvLZI",
    hindiTitle: "गोड़ खड़ुआ ऐ आदितमल",
    romanTitle: "Goad Khadooa Ae Aaditmal",
    artist: "अनुराधा पौडवाल (Anuradha Paudwal)",
    year: "1997",
  },
  {
    id: "s_65",
    trackNum: "065",
    videoId: "uHBj_cnbDmQ",
    hindiTitle: "कोपी कोपी बोलले सुरुज देव",
    romanTitle: "Kopi Kopi Bolale Suruj Dev",
    artist: "अनुराधा पौडवाल (Anuradha Paudwal)",
    year: "1996",
  },
  {
    id: "s_66",
    trackNum: "066",
    videoId: "sSDPerVSruA",
    hindiTitle: "भोरे भोरे बोलेली चुहुचुहिया",
    romanTitle: "Bhore Bhore Boleli Chuchuiya",
    artist: "शारदा सिन्हा (Sharda Sinha)",
    year: "1995",
  },
  {
    id: "s_67",
    trackNum: "067",
    videoId: "e7voBFN2MZ0",
    hindiTitle: "सीतामढ़ी दरभंगा जोगबनी सुबह सहर",
    romanTitle: "Sitamarhi Darbhanga Jogbani Subah Sahar",
    artist: "कल्पना पटवारी (Kalpana Patowary)",
    year: "2015",
  },
];
